# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UR_playground_mainwindow03.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 785)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 80))
        self.frame.setMaximumSize(QtCore.QSize(350, 140))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.valToolLength = QtWidgets.QLineEdit(self.frame)
        self.valToolLength.setMaximumSize(QtCore.QSize(16777215, 20))
        self.valToolLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valToolLength.setObjectName("valToolLength")
        self.horizontalLayout_2.addWidget(self.valToolLength)
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.valRobotIP = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valRobotIP.sizePolicy().hasHeightForWidth())
        self.valRobotIP.setSizePolicy(sizePolicy)
        self.valRobotIP.setMaximumSize(QtCore.QSize(100, 20))
        self.valRobotIP.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valRobotIP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valRobotIP.setObjectName("valRobotIP")
        self.gridLayout_2.addWidget(self.valRobotIP, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.valAccell = QtWidgets.QLineEdit(self.frame)
        self.valAccell.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valAccell.setObjectName("valAccell")
        self.gridLayout_5.addWidget(self.valAccell, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 1, 0, 1, 1)
        self.valSpeed = QtWidgets.QLineEdit(self.frame)
        self.valSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valSpeed.setObjectName("valSpeed")
        self.gridLayout_5.addWidget(self.valSpeed, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 0, 1, 1, 1)
        self.btnApplyRobotSettings = QtWidgets.QPushButton(self.frame)
        self.btnApplyRobotSettings.setObjectName("btnApplyRobotSettings")
        self.gridLayout_3.addWidget(self.btnApplyRobotSettings, 1, 0, 1, 3)
        self.verticalLayout_7.addWidget(self.frame)
        self.svgFileSettings = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.svgFileSettings.sizePolicy().hasHeightForWidth())
        self.svgFileSettings.setSizePolicy(sizePolicy)
        self.svgFileSettings.setMinimumSize(QtCore.QSize(350, 260))
        self.svgFileSettings.setMaximumSize(QtCore.QSize(350, 16777215))
        self.svgFileSettings.setBaseSize(QtCore.QSize(0, 0))
        self.svgFileSettings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.svgFileSettings.setAutoFillBackground(False)
        self.svgFileSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.svgFileSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.svgFileSettings.setObjectName("svgFileSettings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.svgFileSettings)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SVGFile = QtWidgets.QHBoxLayout()
        self.SVGFile.setObjectName("SVGFile")
        self.label_5 = QtWidgets.QLabel(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.SVGFile.addWidget(self.label_5)
        self.valFileName = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valFileName.setMinimumSize(QtCore.QSize(0, 22))
        self.valFileName.setObjectName("valFileName")
        self.SVGFile.addWidget(self.valFileName)
        self.btnSelectFile = QtWidgets.QPushButton(self.svgFileSettings)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.SVGFile.addWidget(self.btnSelectFile)
        self.SVGFile.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.SVGFile)
        self.line_3 = QtWidgets.QFrame(self.svgFileSettings)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.Origin = QtWidgets.QHBoxLayout()
        self.Origin.setContentsMargins(-1, -1, 0, -1)
        self.Origin.setSpacing(8)
        self.Origin.setObjectName("Origin")
        self.Origin_2 = QtWidgets.QGridLayout()
        self.Origin_2.setObjectName("Origin_2")
        self.label_12 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_12.setObjectName("label_12")
        self.Origin_2.addWidget(self.label_12, 1, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_10.setObjectName("label_10")
        self.Origin_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_9.setObjectName("label_9")
        self.Origin_2.addWidget(self.label_9, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_13.setObjectName("label_13")
        self.Origin_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_11.setObjectName("label_11")
        self.Origin_2.addWidget(self.label_11, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_8.setObjectName("label_8")
        self.Origin_2.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_7.setObjectName("label_7")
        self.Origin_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.valOriginZ = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginZ.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginZ.setObjectName("valOriginZ")
        self.Origin_2.addWidget(self.valOriginZ, 0, 5, 1, 1)
        self.valOriginX = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginX.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginX.setObjectName("valOriginX")
        self.Origin_2.addWidget(self.valOriginX, 0, 1, 1, 1)
        self.valOriginRy = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginRy.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginRy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginRy.setObjectName("valOriginRy")
        self.Origin_2.addWidget(self.valOriginRy, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_4.setObjectName("label_4")
        self.Origin_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.valOriginRx = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginRx.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginRx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginRx.setObjectName("valOriginRx")
        self.Origin_2.addWidget(self.valOriginRx, 1, 1, 1, 1)
        self.valOriginY = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginY.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginY.setObjectName("valOriginY")
        self.Origin_2.addWidget(self.valOriginY, 0, 3, 1, 1)
        self.valOriginRz = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valOriginRz.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOriginRz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOriginRz.setObjectName("valOriginRz")
        self.Origin_2.addWidget(self.valOriginRz, 1, 5, 1, 1)
        self.Origin.addLayout(self.Origin_2)
        self.verticalLayout_2.addLayout(self.Origin)
        self.line = QtWidgets.QFrame(self.svgFileSettings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.PlungeMoveTol = QtWidgets.QGridLayout()
        self.PlungeMoveTol.setObjectName("PlungeMoveTol")
        self.label_16 = QtWidgets.QLabel(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.PlungeMoveTol.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.PlungeMoveTol.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_23.setObjectName("label_23")
        self.PlungeMoveTol.addWidget(self.label_23, 5, 2, 1, 1)
        self.valMove = QtWidgets.QLineEdit(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valMove.sizePolicy().hasHeightForWidth())
        self.valMove.setSizePolicy(sizePolicy)
        self.valMove.setMinimumSize(QtCore.QSize(0, 22))
        self.valMove.setMaximumSize(QtCore.QSize(70, 16777215))
        self.valMove.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valMove.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valMove.setObjectName("valMove")
        self.PlungeMoveTol.addWidget(self.valMove, 3, 1, 1, 1)
        self.valPlunge = QtWidgets.QLineEdit(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valPlunge.sizePolicy().hasHeightForWidth())
        self.valPlunge.setSizePolicy(sizePolicy)
        self.valPlunge.setMinimumSize(QtCore.QSize(0, 22))
        self.valPlunge.setMaximumSize(QtCore.QSize(70, 16777215))
        self.valPlunge.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valPlunge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valPlunge.setObjectName("valPlunge")
        self.PlungeMoveTol.addWidget(self.valPlunge, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.PlungeMoveTol.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_17.setObjectName("label_17")
        self.PlungeMoveTol.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_15.setObjectName("label_15")
        self.PlungeMoveTol.addWidget(self.label_15, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.PlungeMoveTol.addItem(spacerItem, 3, 3, 1, 1)
        self.valTolerance = QtWidgets.QLineEdit(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valTolerance.sizePolicy().hasHeightForWidth())
        self.valTolerance.setSizePolicy(sizePolicy)
        self.valTolerance.setMinimumSize(QtCore.QSize(0, 22))
        self.valTolerance.setMaximumSize(QtCore.QSize(70, 16777215))
        self.valTolerance.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valTolerance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valTolerance.setObjectName("valTolerance")
        self.PlungeMoveTol.addWidget(self.valTolerance, 5, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_35.setObjectName("label_35")
        self.PlungeMoveTol.addWidget(self.label_35, 6, 0, 1, 1)
        self.valBlend = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valBlend.setMaximumSize(QtCore.QSize(70, 16777215))
        self.valBlend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valBlend.setObjectName("valBlend")
        self.PlungeMoveTol.addWidget(self.valBlend, 6, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_36.setObjectName("label_36")
        self.PlungeMoveTol.addWidget(self.label_36, 6, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.PlungeMoveTol.addWidget(self.label_18, 1, 0, 1, 1)
        self.valScale = QtWidgets.QLineEdit(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valScale.sizePolicy().hasHeightForWidth())
        self.valScale.setSizePolicy(sizePolicy)
        self.valScale.setMinimumSize(QtCore.QSize(0, 22))
        self.valScale.setMaximumSize(QtCore.QSize(70, 16777215))
        self.valScale.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valScale.setObjectName("valScale")
        self.PlungeMoveTol.addWidget(self.valScale, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_21.setObjectName("label_21")
        self.PlungeMoveTol.addWidget(self.label_21, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.PlungeMoveTol)
        self.line_2 = QtWidgets.QFrame(self.svgFileSettings)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.ColOpa = QtWidgets.QGridLayout()
        self.ColOpa.setObjectName("ColOpa")
        self.label_25 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_25.setObjectName("label_25")
        self.ColOpa.addWidget(self.label_25, 1, 2, 1, 1)
        self.valColorFactor = QtWidgets.QLineEdit(self.svgFileSettings)
        self.valColorFactor.setMinimumSize(QtCore.QSize(0, 22))
        self.valColorFactor.setMaximumSize(QtCore.QSize(50, 16777215))
        self.valColorFactor.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valColorFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valColorFactor.setObjectName("valColorFactor")
        self.ColOpa.addWidget(self.valColorFactor, 0, 3, 1, 1)
        self.checkUseColor = QtWidgets.QCheckBox(self.svgFileSettings)
        self.checkUseColor.setObjectName("checkUseColor")
        self.ColOpa.addWidget(self.checkUseColor, 0, 0, 1, 1)
        self.valOpacityFactor = QtWidgets.QLineEdit(self.svgFileSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valOpacityFactor.sizePolicy().hasHeightForWidth())
        self.valOpacityFactor.setSizePolicy(sizePolicy)
        self.valOpacityFactor.setMinimumSize(QtCore.QSize(50, 22))
        self.valOpacityFactor.setMaximumSize(QtCore.QSize(50, 16777215))
        self.valOpacityFactor.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.valOpacityFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valOpacityFactor.setObjectName("valOpacityFactor")
        self.ColOpa.addWidget(self.valOpacityFactor, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_24.setObjectName("label_24")
        self.ColOpa.addWidget(self.label_24, 0, 2, 1, 1)
        self.checkUseOpacity = QtWidgets.QCheckBox(self.svgFileSettings)
        self.checkUseOpacity.setChecked(False)
        self.checkUseOpacity.setObjectName("checkUseOpacity")
        self.ColOpa.addWidget(self.checkUseOpacity, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_26.setObjectName("label_26")
        self.ColOpa.addWidget(self.label_26, 0, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.svgFileSettings)
        self.label_27.setObjectName("label_27")
        self.ColOpa.addWidget(self.label_27, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ColOpa.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.ColOpa)
        self.line_4 = QtWidgets.QFrame(self.svgFileSettings)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.btnApplySVGSettings = QtWidgets.QPushButton(self.svgFileSettings)
        self.btnApplySVGSettings.setObjectName("btnApplySVGSettings")
        self.verticalLayout_2.addWidget(self.btnApplySVGSettings)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addWidget(self.svgFileSettings)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 0, 1, 1)
        self.labelCurrentAction = QtWidgets.QLabel(self.frame_2)
        self.labelCurrentAction.setText("")
        self.labelCurrentAction.setObjectName("labelCurrentAction")
        self.gridLayout_4.addWidget(self.labelCurrentAction, 3, 1, 1, 1)
        self.btnSend = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSend.sizePolicy().hasHeightForWidth())
        self.btnSend.setSizePolicy(sizePolicy)
        self.btnSend.setObjectName("btnSend")
        self.gridLayout_4.addWidget(self.btnSend, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 10)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 1, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.frame_2)
        self.btnConnect.setEnabled(False)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_4.addWidget(self.btnConnect, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 4, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(400, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.widgetPreview = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPreview.sizePolicy().hasHeightForWidth())
        self.widgetPreview.setSizePolicy(sizePolicy)
        self.widgetPreview.setObjectName("widgetPreview")
        self.verticalLayout_6.addWidget(self.widgetPreview)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Log = QtWidgets.QWidget()
        self.Log.setObjectName("Log")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Log)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 571, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkGrid = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkGrid.setChecked(False)
        self.checkGrid.setObjectName("checkGrid")
        self.gridLayout_9.addWidget(self.checkGrid, 3, 0, 1, 1)
        self.checkPlatform = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkPlatform.setChecked(True)
        self.checkPlatform.setObjectName("checkPlatform")
        self.gridLayout_9.addWidget(self.checkPlatform, 0, 0, 1, 1)
        self.checkBoxes = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxes.setChecked(True)
        self.checkBoxes.setObjectName("checkBoxes")
        self.gridLayout_9.addWidget(self.checkBoxes, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_9)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btnPlay = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnPlay.setEnabled(True)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout_7.addWidget(self.btnPlay, 1, 0, 1, 1)
        self.sliderPlay = QtWidgets.QSlider(self.gridLayoutWidget)
        self.sliderPlay.setEnabled(True)
        self.sliderPlay.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPlay.setObjectName("sliderPlay")
        self.gridLayout_7.addWidget(self.sliderPlay, 1, 1, 1, 1)
        self.btnCheck = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCheck.setObjectName("btnCheck")
        self.gridLayout_7.addWidget(self.btnCheck, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.Log, "")
        self.Preview = QtWidgets.QWidget()
        self.Preview.setObjectName("Preview")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Preview)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.Preview)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.txtLog = QtWidgets.QPlainTextEdit(self.Preview)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout.addWidget(self.txtLog)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.Preview, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.valRobotIP)
        MainWindow.setTabOrder(self.valRobotIP, self.valToolLength)
        MainWindow.setTabOrder(self.valToolLength, self.valSpeed)
        MainWindow.setTabOrder(self.valSpeed, self.valAccell)
        MainWindow.setTabOrder(self.valAccell, self.btnApplyRobotSettings)
        MainWindow.setTabOrder(self.btnApplyRobotSettings, self.valFileName)
        MainWindow.setTabOrder(self.valFileName, self.btnSelectFile)
        MainWindow.setTabOrder(self.btnSelectFile, self.valOriginX)
        MainWindow.setTabOrder(self.valOriginX, self.valOriginY)
        MainWindow.setTabOrder(self.valOriginY, self.valOriginZ)
        MainWindow.setTabOrder(self.valOriginZ, self.valOriginRx)
        MainWindow.setTabOrder(self.valOriginRx, self.valOriginRy)
        MainWindow.setTabOrder(self.valOriginRy, self.valOriginRz)
        MainWindow.setTabOrder(self.valOriginRz, self.valScale)
        MainWindow.setTabOrder(self.valScale, self.valPlunge)
        MainWindow.setTabOrder(self.valPlunge, self.valMove)
        MainWindow.setTabOrder(self.valMove, self.valTolerance)
        MainWindow.setTabOrder(self.valTolerance, self.valBlend)
        MainWindow.setTabOrder(self.valBlend, self.checkUseColor)
        MainWindow.setTabOrder(self.checkUseColor, self.valColorFactor)
        MainWindow.setTabOrder(self.valColorFactor, self.checkUseOpacity)
        MainWindow.setTabOrder(self.checkUseOpacity, self.valOpacityFactor)
        MainWindow.setTabOrder(self.valOpacityFactor, self.btnApplySVGSettings)
        MainWindow.setTabOrder(self.btnApplySVGSettings, self.btnSend)
        MainWindow.setTabOrder(self.btnSend, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.sliderPlay)
        MainWindow.setTabOrder(self.sliderPlay, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.btnConnect)
        MainWindow.setTabOrder(self.btnConnect, self.btnPlay)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.valToolLength.setToolTip(_translate("MainWindow", "Length of tool attached to robot"))
        self.valToolLength.setText(_translate("MainWindow", "50"))
        self.label_31.setText(_translate("MainWindow", "mm"))
        self.label_2.setText(_translate("MainWindow", "Robot IP"))
        self.comboBox.setToolTip(_translate("MainWindow", "Robot Model"))
        self.comboBox.setWhatsThis(_translate("MainWindow", "The Model of the Robot that will be used. Currently only UR5 available, but any UR Robot should work"))
        self.comboBox.setItemText(0, _translate("MainWindow", "UR 5 cb"))
        self.label.setText(_translate("MainWindow", "Robot "))
        self.label_3.setText(_translate("MainWindow", "Tool length"))
        self.valRobotIP.setToolTip(_translate("MainWindow", "Robot IP Address"))
        self.valRobotIP.setWhatsThis(_translate("MainWindow", "THe IP address of the robot. You can find your robots IP by pressing in the upper left corner on the pendant. "))
        self.valRobotIP.setText(_translate("MainWindow", "192.168.178.20"))
        self.valAccell.setText(_translate("MainWindow", "75"))
        self.label_28.setText(_translate("MainWindow", "Speed"))
        self.label_29.setText(_translate("MainWindow", "Accell."))
        self.valSpeed.setText(_translate("MainWindow", "90"))
        self.label_32.setText(_translate("MainWindow", "%"))
        self.label_34.setText(_translate("MainWindow", "%"))
        self.btnApplyRobotSettings.setToolTip(_translate("MainWindow", "Press to apply Robot settings"))
        self.btnApplyRobotSettings.setText(_translate("MainWindow", "Apply Robot Settings"))
        self.label_5.setText(_translate("MainWindow", "SVG File"))
        self.valFileName.setToolTip(_translate("MainWindow", "SVG File to be loaded "))
        self.btnSelectFile.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Load svg file</p></body></html>"))
        self.btnSelectFile.setText(_translate("MainWindow", "load file"))
        self.label_12.setText(_translate("MainWindow", "Rz"))
        self.label_10.setText(_translate("MainWindow", "Rx"))
        self.label_9.setText(_translate("MainWindow", "Z"))
        self.label_13.setText(_translate("MainWindow", "Origin Rotation"))
        self.label_11.setText(_translate("MainWindow", "Ry"))
        self.label_8.setText(_translate("MainWindow", "Y"))
        self.label_7.setText(_translate("MainWindow", "X"))
        self.valOriginZ.setText(_translate("MainWindow", "45"))
        self.valOriginX.setText(_translate("MainWindow", "-200"))
        self.valOriginRy.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Origin Position"))
        self.valOriginRx.setText(_translate("MainWindow", "0"))
        self.valOriginY.setText(_translate("MainWindow", "-300"))
        self.valOriginRz.setText(_translate("MainWindow", "180"))
        self.label_16.setText(_translate("MainWindow", "Plunge Depth"))
        self.label_14.setText(_translate("MainWindow", "Move height"))
        self.label_23.setText(_translate("MainWindow", "mm"))
        self.valMove.setText(_translate("MainWindow", "45"))
        self.valPlunge.setText(_translate("MainWindow", "50"))
        self.label_22.setText(_translate("MainWindow", "Tolerance"))
        self.label_17.setText(_translate("MainWindow", "mm"))
        self.label_15.setText(_translate("MainWindow", "mm"))
        self.valTolerance.setText(_translate("MainWindow", "12"))
        self.label_35.setText(_translate("MainWindow", "Blend Radius"))
        self.valBlend.setText(_translate("MainWindow", "3"))
        self.label_36.setText(_translate("MainWindow", "mm"))
        self.label_18.setText(_translate("MainWindow", "Scale"))
        self.valScale.setText(_translate("MainWindow", "100"))
        self.label_21.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", "Opacity Factor"))
        self.valColorFactor.setText(_translate("MainWindow", "100"))
        self.checkUseColor.setText(_translate("MainWindow", "Use Colors (rotation)"))
        self.valOpacityFactor.setText(_translate("MainWindow", "100"))
        self.label_24.setText(_translate("MainWindow", "Color Factor"))
        self.checkUseOpacity.setText(_translate("MainWindow", "Use Opacity (depth)"))
        self.label_26.setText(_translate("MainWindow", "%"))
        self.label_27.setText(_translate("MainWindow", "%"))
        self.btnApplySVGSettings.setText(_translate("MainWindow", "Apply SVG Settings"))
        self.label_30.setText(_translate("MainWindow", "Robot Status:"))
        self.btnSend.setText(_translate("MainWindow", "Send to Robot"))
        self.label_37.setText(_translate("MainWindow", "Current Action:"))
        self.label_33.setText(_translate("MainWindow", "not connected"))
        self.btnConnect.setText(_translate("MainWindow", "connect to Robot"))
        self.label_19.setText(_translate("MainWindow", "Progress:"))
        self.label_6.setText(_translate("MainWindow", "Preview"))
        self.widgetPreview.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Robot Toolpath Preview</p></body></html>"))
        self.checkGrid.setText(_translate("MainWindow", "Show Grid"))
        self.checkPlatform.setText(_translate("MainWindow", "Show Platform"))
        self.checkBoxes.setText(_translate("MainWindow", "Show Boxes"))
        self.btnPlay.setText(_translate("MainWindow", "Play"))
        self.btnCheck.setText(_translate("MainWindow", "Check Toolpath"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log), _translate("MainWindow", "Preview Settings"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "INFO"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "DEBUG"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "WARNING"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "ERROR"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "CRITICAL"))
        self.txtLog.setToolTip(_translate("MainWindow", "Shows logging messages. Current level set to INFO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preview), _translate("MainWindow", "Log"))
